### ISSUE TITLE
Install required library fails

### ISSUE THREAD

**Issue by gmckinley4** [cvezalis/oracledb-ansible#7]
When I run the playbook, I get a failure on the install required library fails.

failed: [oradb] (item=[u'packages_list']) => {"changed": false, "failed": true, "item": ["packages_list"], "msg": "No package matching 'packages_list' found available, installed or updated", "rc": 126, "results": ["No package matching 'packages_list' found available, installed or updated"]}

**Comment by cvezalis** [comment]
I have update playbook to be compatible with ansible 2 syntax
